### PR TITLE
Nixpkgs update, and crypton-connection upgrade

### PR DESCRIPTION
**Pull request by ErnestKz**
Seems like `crypton-connection` is superseding `connection`, and a large portion of the Haskell ecosystem has done the migration. Having both connection and crypton-connection in a project causes a conflict on the `tls` version.

Links:
- https://hackage.haskell.org/package/crypton-connection-0.3.1
- https://hackage.haskell.org/package/connection

### CODE REVIEW

**Comment by ErnestKz** [comment]
After the nixpkgs update, `vault` has become unfree. It is only a part of the dev dependencies:

https://github.com/channable/vaultenv/blob/ee9728e9e00003f7216a0a14f20c5ac6d23d64f2/default.nix#L11

**Comment by ErnestKz** [comment]
Since this project already works as a binary in it's current release. We can perform a release once we addressed this issue: https://github.com/channable/vaultenv/issues/141

**Comment by alex-mckenna** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @alex-mckenna, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as af4d544e79011035e44e46dde6cde269fa96f450, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/e6276fff-5c5f-4346-bdd9-501bc1da970f?pipeline_id=688927c1-ea43-4356-99f2-a5b42a06cf97) started.

**Pull request merged**
