### PR TITLE
Remove cachix from default.nix

### PR DESCRIPTION
**Pull request by d-goncalves**
# Description

Removes cachix from default.nix

### CODE REVIEW

**Review by ReinierMaas — APPROVED** [review]
LGTM! 🚀

**Comment by d-goncalves** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @d-goncalves, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 26ecc0f00c26271c66b145f7ce17e4804fb2f5bf, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/f31ee786-c932-4b04-81f0-35118073ff7e?pipeline_id=5c03817f-f30b-4021-9a16-903e7586f4ac) started.

**Pull request merged**
