### PR TITLE
Fix typo in Forbidden error message

### PR DESCRIPTION
**Pull request by ruuda**
Title/diff say it all.

### CODE REVIEW

**Review by bertptrs — APPROVED** [review]
Was wondering whether you'd actually do it. LGTM. @OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Your merge request has been denied, because merging on Fridays is not recommended. To override this behaviour use the command `merge on Friday`.

**Comment by bertptrs** [comment]
@OpsBotPrime merge on Friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @bertptrs, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as e2b81c8657adad9f0c768be151398a4ebe4f1fbc, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/2d0e93b4-3fe0-47d1-9dcb-312a7da925eb?pipeline_id=e2c48e9a-219f-4af6-9cb8-79a5846079b8) started.

**Comment by ruuda** [comment]
Ik ben een pannenkoek. My typo fix introduces another typo :woman_facepalming:

**Pull request merged**
