### PR TITLE
Add Kubernetes and Github Auth

### LINKED ISSUE #121: Authenticate with GitHub
Similar to #116, we want to be able to authenticate with a GitHub account.
Vault supports this authentication flow: https://www.vaultproject.io/docs/auth/github.
This makes it possible to not use the root token (which can be a security risk).

### PR DESCRIPTION
**Pull request by Riscky**
closes #121

This PR adds two new authentication options to Vaultenv, both of which do not require a root token.
This PR is based of #116, and most of the work is done by @ruuda (thanks!).

Next to the work in that PR, which never got merged, this PR adds a new option `--github-token`, which is an alternative to `--vault-token` or `--kubernetes-role`. If the `--github-token` is supplied, Vaultenv will use this token to get a Vault token that is used for subsequent requests. The provided token should be a Github Personal Access Token with the `org:read` scope on the relevant organization. See also https://www.vaultproject.io/docs/auth/github

This feature has been tested locally, and works nicely.
I did not yet add automated tests, because this requires a setup involving a Github account.

### CODE REVIEW

**Review by ReinierMaas — APPROVED** [review]
LGTM!

I have a single comment on the consistency of the code itself. Other pointers are about the testing framework. If those are resolved we can merge the code.

**Comment by Riscky** [comment]
I've taken some time to get the Kubernetes tests working, but I haven't succeeded.
All steps run, but Vaultenv does not seem to get a response when trying to access `/v1/auth/kubernetes/login`.
Since the Kubernetes tests are not working properly, I haven't included @ReinierMaas's suggestions, as I cannot verify the changes.
@ruuda, if you can help out here it would be much appreciated.

I have enabled most integration tests in CI, except for the retry tests, which need the SIGSTOP signal to actually stop vaultenv, which does not happen in our CI apparently.

**Comment by Riscky** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @Riscky, rebasing now.

**Pull request merged**
