### PR TITLE
Add a bit more logging at info level

### PR DESCRIPTION
**Pull request by ruuda**
I was trying to get things to run with the new Kubernetes authentication introduced in #122, but I ran into some issues. This additional logging helped me to diagnose the issue.

It’s a bit ugly to replicate the `getOptionsValue oLogLevel (cCliOptions context) <= Info`, maybe it makes sense write small function for this.

Off topic: the issue I was facing (writing this down here in case future visitors are facing the same issue). The policy associated with the role did not have permission to read `/sys/mounts`. Vaultenv did not fail on this when it requested the mounts, but it caused it to make a request to `/v1/secret/mypath` instead of `/v1/secret/data/mypath`. The additional logging helps diagnose this. The solution was to add

```hctl
path "sys/mounts" {
  capabilities = ["read"]
}
```

to the policy associated with the role in Vault. Possibly Vaultenv could do some validation on the response there, I haven’t looked into it.

### CODE REVIEW

**Review by Riscky — APPROVED** [review]
LGTM

**Comment by OpsBotPrime** [comment]
Rebased as 5c48fdfab52a29ab84da0026afb21ad5ead8b78b, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/225493b8-b076-4b14-bf04-5f18dfdca52b?pipeline_id=4466fc27-43e0-4c1e-837f-019941de5845) started.

**Comment by OpsBotPrime** [comment]
The build succeeded.

**Pull request merged**
