### PR TITLE
Update Nix to 2.10.3 on CI 

### PR DESCRIPTION
**Pull request by adrianotm**

### CODE REVIEW

**Review by FPtje — APPROVED** [review]
Thanks!

**Comment by adrianotm** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @adrianotm, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 285463d13c907d29f10fb8c900a5704a8d6878e3, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/9459847f-5a23-4f74-aa9b-6fad9d0b5f5f?pipeline_id=cda93340-085b-4f52-91ef-21488c92cd77) started.

**Pull request merged**
